<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-02-08 17:23
=======
# Generated by Django 2.2.18 on 2021-02-11 02:20
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("mainapp", "0002_product"),
=======
        ('mainapp', '0002_product'),
>>>>>>> master
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Contact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=50, verbose_name="номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="электронная почта")),
                ("city", models.CharField(default="Москва", max_length=128, verbose_name="город")),
                ("address", models.CharField(max_length=254, verbose_name="адресс")),
=======
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('city', models.CharField(default='Москва', max_length=128, verbose_name='город')),
                ('address', models.CharField(max_length=254, verbose_name='адресс')),
>>>>>>> master
            ],
        ),
    ]
