<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-02-11 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 2.2.18 on 2021-02-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0004_fill_db"),
=======
        ('mainapp', '0004_fill_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> master
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Basket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="количество")),
                ("add_datetime", models.DateTimeField(auto_now_add=True, verbose_name="время добавления")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mainapp.Product")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basket", to=settings.AUTH_USER_MODEL
                    ),
                ),
=======
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
>>>>>>> master
            ],
        ),
    ]
