# Generated by Django 2.2.17 on 2021-03-22 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210317_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 16, 41, 35, 637676, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
